# Generated by Django 5.2.14 on 2026-06-18 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Título')),
                ('authors', models.TextField(blank=True, verbose_name='Autores')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('abstract', models.TextField(blank=True, verbose_name='Resumen')),
                ('keywords', models.TextField(blank=True, verbose_name='Palabras clave')),
                ('doi', models.CharField(blank=True, max_length=255, verbose_name='DOI')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Fuente')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('included', 'Incluido'), ('excluded', 'Excluido'), ('review', 'Revisar después')], default='pending', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('excel_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.excelupload')),
            ],
        ),
    ]
