# Generated by Django 5.2.14 on 2026-06-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='external_id',
            field=models.CharField(blank=True, help_text='Ej.: EID de Scopus o UT de Web of Science.', max_length=255, verbose_name='Identificador externo'),
        ),
        migrations.AddField(
            model_name='article',
            name='journal',
            field=models.CharField(blank=True, max_length=255, verbose_name='Revista o fuente de publicación'),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='source_database',
            field=models.CharField(choices=[('scopus', 'Scopus'), ('wos', 'Web of Science'), ('unknown', 'No identificada')], default='unknown', max_length=20, verbose_name='Base de datos de origen'),
        ),
    ]
